-- CARGA BOM (producto_componentes) - recetas de platinas por producto
-- Une producto(SKU) con material(PNNN). visible_cliente=false (interno).
-- Incluye receta de polea con flauta x2 y doble polea x2, y jlocks por rack.
-- Idempotente: borra el BOM de platinas previo de estos productos y reinserta.
delete from producto_componentes pc using productos p
 where pc.producto_id=p.id and pc.material_id is not null
   and p.sku in ('1RaPF5f','1RaPF5p','1RaPF10V2','1RaS15','1RaS7','1RaAL1','1RaP10','1RaP20','1RaSR5','5RaSS22','2RiPi1m','2RiPi3m','6BaPle','6BaPla','3BaSen180','3BaM','3BaV','3BrTul','3Fond','3Land','3LeRo','5HQRo','7DcBar','7DapBar','3PoMov','3SoSeSe','3GaAL','8TaAlmAgPo','3ADR','3PoRa2','8PortBaPa3','8PortBaPa5','8AlmBarDP6','8AlmBanc','3TargAl','7CuDo','7CuIndivi','3SmithCmov');

insert into producto_componentes (producto_id, material_id, categoria, descripcion, cantidad, visible_cliente)
select p.id, m.id, v.categoria, v.descripcion, v.cantidad, false
from (values
  ('1RaPF5f','P014','Platina nivelador','platineria',2),
  ('1RaPF5f','P005','Platina xbean','platineria',8),
  ('1RaPF5f','P002','Platina barra sencilla','platineria',2),
  ('1RaPF5f','i3D001','Tapa columna 70x70','impresion_3d',2),
  ('1RaPF5f','P011','Platina pin jlock','platineria',2),
  ('1RaPF5f','P012','Platina aleta jlock','platineria',2),
  ('1RaPF5f','P013','Platina seguridad jlock','platineria',2),
  ('1RaPF5p','P014','Platina nivelador','platineria',2),
  ('1RaPF5p','P005','Platina xbean','platineria',4),
  ('1RaPF5p','P043','Platina pared pf5 abatible','platineria',4),
  ('1RaPF5p','P044','Platina sanduche pf5 abatible','platineria',8),
  ('1RaPF5p','P045','Platina en C barra desmontable pf5 abatible','platineria',2),
  ('1RaPF5p','i3D001','Tapa columna 70x70','impresion_3d',2),
  ('1RaPF5p','P011','Platina pin jlock','platineria',2),
  ('1RaPF5p','P012','Platina aleta jlock','platineria',2),
  ('1RaPF5p','P013','Platina seguridad jlock','platineria',2),
  ('1RaPF10V2','P014','Platina nivelador','platineria',4),
  ('1RaPF10V2','P002','Platina barra sencilla','platineria',4),
  ('1RaPF10V2','P006','Platina xbean pequena','platineria',12),
  ('1RaPF10V2','P005','Platina xbean','platineria',4),
  ('1RaPF10V2','i3D001','Tapa columna 70x70','impresion_3d',4),
  ('1RaPF10V2','P011','Platina pin jlock','platineria',2),
  ('1RaPF10V2','P012','Platina aleta jlock','platineria',2),
  ('1RaPF10V2','P013','Platina seguridad jlock','platineria',2),
  ('1RaS15','P001','Platina base','platineria',4),
  ('1RaS15','P005','Platina xbean','platineria',8),
  ('1RaS15','P002','Platina barra sencilla','platineria',4),
  ('1RaS15','i3D001','Tapa columna 70x70','impresion_3d',4),
  ('1RaS15','P011','Platina pin jlock','platineria',2),
  ('1RaS15','P012','Platina aleta jlock','platineria',2),
  ('1RaS15','P013','Platina seguridad jlock','platineria',2),
  ('1RaS7','P001','Platina base','platineria',4),
  ('1RaS7','P005','Platina xbean','platineria',6),
  ('1RaS7','P002','Platina barra sencilla','platineria',2),
  ('1RaS7','i3D001','Tapa columna 70x70','impresion_3d',4),
  ('1RaS7','P011','Platina pin jlock','platineria',2),
  ('1RaS7','P012','Platina aleta jlock','platineria',2),
  ('1RaS7','P013','Platina seguridad jlock','platineria',2),
  ('1RaAL1','P001','Platina base','platineria',4),
  ('1RaAL1','P002','Platina barra sencilla','platineria',8),
  ('1RaAL1','i3D001','Tapa columna 70x70','impresion_3d',4),
  ('1RaAL1','P011','Platina pin jlock','platineria',2),
  ('1RaAL1','P012','Platina aleta jlock','platineria',2),
  ('1RaAL1','P013','Platina seguridad jlock','platineria',2),
  ('1RaP10','P001','Platina base','platineria',2),
  ('1RaP10','P002','Platina barra sencilla','platineria',6),
  ('1RaP10','i3D001','Tapa columna 70x70','impresion_3d',2),
  ('1RaP10','P011','Platina pin jlock','platineria',2),
  ('1RaP10','P012','Platina aleta jlock','platineria',2),
  ('1RaP10','P013','Platina seguridad jlock','platineria',2),
  ('1RaP20','P001','Platina base','platineria',4),
  ('1RaP20','P007','Platina union triangular','platineria',8),
  ('1RaP20','P005','Platina xbean','platineria',10),
  ('1RaP20','P002','Platina barra sencilla','platineria',2),
  ('1RaP20','P079','Platina pasamanos P20','platineria',2),
  ('1RaP20','i3D001','Tapa columna 70x70','impresion_3d',4),
  ('1RaP20','P011','Platina pin jlock','platineria',2),
  ('1RaP20','P012','Platina aleta jlock','platineria',2),
  ('1RaP20','P013','Platina seguridad jlock','platineria',2),
  ('1RaSR5','P002','Platina barra sencilla','platineria',4),
  ('1RaSR5','P006','Platina xbean pequena','platineria',4),
  ('1RaSR5','P007','Platina union triangular','platineria',8),
  ('1RaSR5','P046','Platina con angulo terminacion tubos','platineria',4),
  ('1RaSR5','i3D001','Tapa columna 70x70','impresion_3d',4),
  ('1RaSR5','P011','Platina pin jlock','platineria',2),
  ('1RaSR5','P012','Platina aleta jlock','platineria',2),
  ('1RaSR5','P013','Platina seguridad jlock','platineria',2),
  ('5RaSS22','P007','Platina union triangular','platineria',4),
  ('2RiPi1m','P001','Platina base','platineria',4),
  ('2RiPi1m','P002','Platina barra sencilla','platineria',8),
  ('2RiPi1m','P004','Platina pie amigo barra sencilla','platineria',4),
  ('2RiPi1m','i3D001','Tapa columna 70x70','impresion_3d',4),
  ('2RiPi1m','P011','Platina pin jlock','platineria',2),
  ('2RiPi1m','P012','Platina aleta jlock','platineria',2),
  ('2RiPi1m','P013','Platina seguridad jlock','platineria',2),
  ('2RiPi3m','P001','Platina base','platineria',6),
  ('2RiPi3m','P002','Platina barra sencilla','platineria',14),
  ('2RiPi3m','P004','Platina pie amigo barra sencilla','platineria',10),
  ('2RiPi3m','i3D001','Tapa columna 70x70','impresion_3d',6),
  ('2RiPi3m','P011','Platina pin jlock','platineria',2),
  ('2RiPi3m','P012','Platina aleta jlock','platineria',2),
  ('2RiPi3m','P013','Platina seguridad jlock','platineria',2),
  ('6BaPle','P036','Platina centro basculante banco','platineria',1),
  ('6BaPle','P037','Platina asiento banco','platineria',1),
  ('6BaPle','P038','Platina espaldar banco','platineria',1),
  ('6BaPle','P039','Platina en C soporte asiento banco','platineria',1),
  ('6BaPle','P040','Platina en C soporte espaldar banco','platineria',1),
  ('6BaPle','P041','Platina en C posiciones asiento banco','platineria',2),
  ('6BaPle','P042','Platina en C posiciones espaldar banco','platineria',2),
  ('6BaPla','i3D001','Tapa columna 70x70','impresion_3d',4),
  ('6BaPla','P047','Platina llantas','platineria',2),
  ('3BaSen180','P002','Platina barra sencilla','platineria',2),
  ('3BaSen180','P004','Platina pie amigo barra sencilla','platineria',2),
  ('3BaM','P005','Platina xbean','platineria',2),
  ('3BaV','i3D001','Tapa columna 70x70','impresion_3d',2),
  ('3BaV','P005','Platina xbean','platineria',2),
  ('3BrTul','P009','Platina pie amigo soporte seguridad sentadilla','platineria',2),
  ('3BrTul','P008','Platina soporte seguridad sentadilla','platineria',1),
  ('3BrTul','i3D001','Tapa columna 70x70','impresion_3d',1),
  ('3Fond','P019','Platina fondo en rack','platineria',2),
  ('3Fond','P020','Platina separador fondo a rack','platineria',1),
  ('3Land','P003','Platina en C landmine','platineria',1),
  ('3LeRo','P017','Platina tope leg roller','platineria',1),
  ('3LeRo','P018','Platina tapa leg roller','platineria',1),
  ('5HQRo','P031','Platina hqroller','platineria',2),
  ('7DcBar','P019','Platina fondo en rack','platineria',2),
  ('7DcBar','P020','Platina separador fondo a rack','platineria',1),
  ('7DcBar','P055','Platina pull up dc bar','platineria',2),
  ('7DcBar','P056','Platina pie amigo pull up dc bar','platineria',2),
  ('7DcBar','P054','Platina pared dc bar','platineria',4),
  ('7DapBar','P060','Platina pull up dap bar','platineria',2),
  ('7DapBar','P059','Platina union dap bar','platineria',1),
  ('7DapBar','P057','Platina pared dap bar','platineria',1),
  ('7DapBar','P058','Platina gancho pared dap bar','platineria',4),
  ('3PoMov','P029','Platina bloque de peso superior de polea','platineria',1),
  ('3PoMov','P030','Platina bloque de peso intermedio de polea','platineria',17),
  ('3PoMov','P025','Platina superior guia graduable de polea','platineria',1),
  ('3PoMov','P024','Platina inferior guias de polea','platineria',1),
  ('3PoMov','P026','Platina selectora de peso de polea','platineria',1),
  ('3PoMov','P021','Platina tapa de polea','platineria',2),
  ('3PoMov','P022','Platina triangular sup e inf de polea','platineria',1),
  ('3PoMov','P027','Platina en X carro movil de polea','platineria',2),
  ('3PoMov','P028','Platina en C carro movil de polea','platineria',1),
  ('3PoMov','P061','Platina doble de polea','platineria',2),
  ('3SoSeSe','P008','Platina soporte seguridad sentadilla','platineria',2),
  ('3SoSeSe','P009','Platina pie amigo soporte seguridad sentadilla','platineria',4),
  ('3SoSeSe','P010','Platina seguridad soporte seguridad sentadilla','platineria',2),
  ('3GaAL','P050','Platina gancho almacenador','platineria',1),
  ('8TaAlmAgPo','P064','Platina almacenador de agarres','platineria',1),
  ('8TaAlmAgPo','P050','Platina gancho almacenador','platineria',5),
  ('3ADR','P015','Platina almacenador disco a rack','platineria',1),
  ('3ADR','i3D002','Tapa tubo redondo 48mm','impresion_3d',1),
  ('3PoRa2','P016','Platina almacenador de 2 barras','platineria',1),
  ('8PortBaPa3','P062','Platina almacenador 3 barras','platineria',1),
  ('8PortBaPa5','P063','Platina almacenador 5 barras','platineria',1),
  ('8AlmBarDP6','i3D001','Tapa columna 70x70','impresion_3d',4),
  ('8AlmBanc','P080','Platina almacenador banco a pared','platineria',1),
  ('3TargAl','P033','Platina target','platineria',1),
  ('3TargAl','P034','Platina alargue target','platineria',2),
  ('3TargAl','P035','Platina soldar en target','platineria',1),
  ('7CuDo','P077','Platina cuna doble','platineria',1),
  ('7CuDo','P078','Platina pie amigo refuerzo cunas','platineria',3),
  ('7CuIndivi','P076','Platina cuna sencilla','platineria',1),
  ('7CuIndivi','P078','Platina pie amigo refuerzo cunas','platineria',2),
  ('3SmithCmov','P027','Platina en X carro movil de polea','platineria',4),
  ('3SmithCmov','P028','Platina en C carro movil de polea','platineria',2)
) as v(sku,codigo,categoria,descripcion,cantidad)
join productos p on p.sku=v.sku
join materiales m on m.nombre like v.codigo || ' ·%';

-- Verificacion: platinas por producto
select p.sku, p.nombre, count(*) lineas, sum(pc.cantidad) platinas_total
 from producto_componentes pc join productos p on p.id=pc.producto_id
 where pc.material_id is not null group by 1,2 order by 1;